name: Continuous Integration

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and start containers
        run: docker-compose up -d

      - name: Run Maven build inside container
        run: docker-compose exec app mvn clean package -f /source/pom.xml -X

      - name: Stop containers
        run: docker-compose down
